language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
install: cd gatsby/ && yarn install
script: echo "build"
deploy:
  provider: script
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: yarn run deploy
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
