language: ruby
cache: bundler
branches:
  only:
    - master
script:
  - bundle exec jekyll algolia push
rvm:
 - 2.2
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
