# Site settings
title: code & coffee 
email: mail@adrian-philipp.com
description: > 
  This blog is about two passions of Adrian: web development and coffee. 
baseurl: ""
url: "http://adrian-philipp.com" 
twitter_username: adrian_philipp
github_username:  adri

# Build settings
markdown: kramdown
