# Site settings
title: code & coffee
email: mail@adrian-philipp.com
description: >
  This blog is about two passions of Adrian: web development and coffee.
baseurl: ""
url: "http://adrian-philipp.com"

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: codingnightmare

# Social icons
show_social_icons: true
twitter_username: adrian_philipp
github_username:  adri
stackoverflow_id:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /post/:title
paginate: 3
sass:
  compressed: true

algolia:
  application_id: '38DME6L5S7'
  index_name:     'adrian-philipp.com'
  read_only_api_key: 'b1f56fd2be47c4f61ff94bda42d764a2'
  excluded_files:
    - post.html

gems:
  - algoliasearch-jekyll
