# Site settings
title: code & coffee 
email: mail@adrian-philipp.com
description: > 
  This blog is about two passions of Adrian: web development and coffee. 
baseurl: ""
url: "http://adrian-philipp.com" 

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: adri_p

# Social icons
show_social_icons: false
twitter_username: adrian_philipp
github_username:  adri
stackoverflow_id:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown: kramdown
permalink:    pretty
paginate: 3
sass:
  compressed: true
