name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.5.0
        name: Cancel Previous Runs
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ./gatsby/.cache
            ./gatsby/public
            **/node_modules
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}
      - name: Setup git
        run: |
            git config --global user.email "${{ secrets.EMAIL }}"
            git config --global user.name "Adrian Philipp"
      - name: Install dependencies
        run: cd gatsby && yarn install
      - name: Deploy website
        env:
          # This is necessary in order to push a commit to the repo
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        run: cd gatsby && yarn run deploy
