name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.5.0
        name: Cancel Previous Runs
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/cache@v2.1.1
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Gatsby
        uses: actions/cache@v2.1.1
        with:
          path: |
            ./gatsby/.cache
            ./gatsby/public
          key: ${{ runner.os }}-gatsby-v2-${{ hashFiles('./gatsby/.cache/**') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-v2-
      - name: Setup git
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "Adrian Philipp"
      - name: Install dependencies
        run: cd gatsby && yarn install
      - name: Deploy website
        env:
          # This is necessary in order to push a commit to the repo
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        run: cd gatsby && yarn run deploy
