# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: styfle/cancel-workflow-action@0.5.0
        name: Cancel Previous Runs
        with:
          access_token: ${{ github.token }}
      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: 
            ~/gatsby/.cache
            ~/gatsby/node_modules
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}   
          
      - name: Setup git
        run: |
            git config --global user.email "${{ secrets.EMAIL }}"
            git config --global user.name "Adrian Philipp"
      - name: Install dependencies
        run: cd gatsby && yarn install
      - name: Deploy website
        run: cd gatsby && yarn run deploy
    env:
      # This is necessary in order to push a commit to the repo
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
      GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
      GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}
      ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
